# Generated by Django 3.0.7 on 2020-06-04 13:51

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20200604_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone2', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the following format: '02112345678'.", regex='^0\\d{2}\\d{8}$')])),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('website', models.URLField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid Instagram ID.', regex='^(?:(?:http|https):\\/\\/)?(?:www\\.)?(?:instagram\\.com|instagr\\.am)\\/([A-Za-z0-9-_\\.]+)')])),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid Telegram ID.', regex='^(?:(?:http|https):\\/\\/)?(?:www\\.)?(?:telegram\\.me|t\\.me|telegram.dog)\\/([A-Za-z0-9-_\\.]+)$')])),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Saturday'), (2, 'Sunday'), (3, 'Monday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('biz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.Biz')),
            ],
            options={
                'verbose_name': 'Hour',
                'verbose_name_plural': 'Hours',
                'unique_together': {('biz', 'weekday', 'from_hour')},
            },
        ),
    ]
