# Generated by Django 3.0.7 on 2020-06-04 18:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200604_1818'),
        ('biz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biz',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='biz',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.User'),
        ),
        migrations.AlterField(
            model_name='biz',
            name='gallery',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='biz',
            name='instagram',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter a valid Instagram ID.', regex='^(?:(?:http|https):\\/\\/)?(?:www\\.)?(?:instagram\\.com|instagr\\.am)\\/([A-Za-z0-9-_\\.]+)')]),
        ),
        migrations.AlterField(
            model_name='biz',
            name='phone2',
            field=models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the following format: '02112345678'.", regex='^0\\d{2}\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='biz',
            name='telegram',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter a valid Telegram ID.', regex='^(?:(?:http|https):\\/\\/)?(?:www\\.)?(?:telegram\\.me|t\\.me|telegram.dog)\\/([A-Za-z0-9-_\\.]+)$')]),
        ),
        migrations.AlterField(
            model_name='biz',
            name='website',
            field=models.URLField(default='', max_length=50),
        ),
    ]
