# Generated by Django 3.0.5 on 2020-04-27 15:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
