# Generated by Django 3.0.5 on 2020-05-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0004_auto_20200501_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biz',
            name='from_hour',
        ),
        migrations.RemoveField(
            model_name='biz',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='biz',
            name='to_hour',
        ),
        migrations.RemoveField(
            model_name='biz',
            name='weekday',
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Saturday'), (2, 'Sunday'), (3, 'Monday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')], unique=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('biz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.Biz')),
            ],
        ),
    ]
