# Generated by Django 3.0.5 on 2020-05-01 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0005_auto_20200501_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
