# Generated by Django 3.0.5 on 2020-05-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0007_auto_20200502_1700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hours',
            unique_together={('biz', 'weekday', 'from_hour')},
        ),
    ]
