# Generated by Django 3.0.5 on 2020-05-10 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0008_auto_20200504_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz',
            name='phone2',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '02112345678'.", regex='^0\\d{2}\\d{8}$')]),
        ),
    ]
