# Generated by Django 3.0.5 on 2020-05-10 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0010_auto_20200510_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biz',
            name='phone2',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the following format: '02112345678'.", regex='^0\\d{2}\\d{8}$')]),
        ),
    ]
