# Generated by Django 3.0.5 on 2020-05-10 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0011_auto_20200510_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid Instagram ID.', regex='^(?:(?:http|https):\\/\\/)?(?:www\\.)?(?:telegram\\.me|t\\.me)\\/([A-Za-z0-9-_\\.]+)(?:\\/[A-Za-z0-9-_\\.]+)$')]),
        ),
    ]
