# Generated by Django 3.0.6 on 2020-05-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0016_auto_20200511_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hours',
            options={'verbose_name': 'Hour', 'verbose_name_plural': 'Hours'},
        ),
    ]
