# Generated by Django 3.0.14 on 2021-05-19 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('length', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
    ]
